### ISSUE TITLE
Private tests fail as no configuration file is present

### ISSUE THREAD

**Issue by thomasdangl** [se2p/programming-styles-ss-2020-public-tests#45]
The private test 'basic-test' fails because it assumes the program ends gracefully.
However, the current program specifications do not allow a graceful program termination if no configuration file is present as is the case for the private tests.
```
  1) Basic Test
       runs without exceptions()
         Preys and Hunters should raise no exception:
     Error: ENOENT: no such file or directory, open './config.ini'
      at Object.openSync (fs.js:443:3)
      at Object.readFileSync (fs.js:343:35)
      at readConfiguration (/home/preys-and-hunters.js:28:17)
      at loadPlugins (/home/preys-and-hunters.js:36:11)
      at Object.module.exports.main (/home/preys-and-hunters.js:42:2)
      at Context.<anonymous> (test/basic-tests.js:20:17)
```

Potential solutions:
- Change the test such that it expects the exception
- Create a default configuration in the private tests repository

**Comment by alessiogambi** [comment]
@thomasdangl  #46 should have fixed this (I also committed the same update on private tests plus an additional test)
